# Generated by Django 4.1.2 on 2022-12-04 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consolaApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consola',
            name='memoria',
            field=models.CharField(max_length=5),
        ),
    ]
