# Generated by Django 4.1.2 on 2022-11-26 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='trabajador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=15)),
                ('apellido', models.CharField(max_length=15)),
                ('rut', models.CharField(max_length=10)),
                ('telefono', models.IntegerField(max_length=9)),
                ('correo', models.CharField(max_length=35)),
                ('fechaNacimiento', models.DateField()),
            ],
        ),
    ]
