# Generated by Django 4.1.2 on 2022-11-26 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabajador',
            name='telefono',
            field=models.IntegerField(),
        ),
    ]
