# Generated by Django 4.1.2 on 2022-11-26 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evaApp', '0002_alter_trabajador_telefono'),
    ]

    operations = [
        migrations.DeleteModel(
            name='trabajador',
        ),
    ]
