# Generated by Django 4.1.2 on 2022-12-02 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaApp', '0004_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabajador',
            name='compraConsola',
            field=models.IntegerField(default=0),
        ),
    ]
