# Generated by Django 4.1.2 on 2022-12-04 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaApp', '0005_trabajador_compraconsola'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabajador',
            name='compraConsola',
            field=models.CharField(max_length=15),
        ),
    ]
