# Generated by Django 4.1.2 on 2022-12-08 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consolaApp', '0002_alter_consola_memoria'),
        ('evaApp', '0006_alter_trabajador_compraconsola'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trabajador',
            name='compraConsola',
        ),
        migrations.AddField(
            model_name='trabajador',
            name='nombreConsola',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='consolaApp.consola'),
        ),
    ]
