# Generated by Django 4.1.2 on 2022-12-02 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Videojuego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreVideojuego', models.CharField(max_length=30)),
                ('duracion', models.IntegerField()),
                ('edicion', models.CharField(max_length=30)),
                ('genero', models.CharField(max_length=20)),
                ('precio', models.IntegerField()),
                ('cantidadJugadores', models.IntegerField()),
                ('idConsola', models.IntegerField()),
            ],
        ),
    ]
