# Generated by Django 4.1.2 on 2022-12-08 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consolaApp', '0002_alter_consola_memoria'),
        ('videojuegoApp', '0002_remove_videojuego_idconsola_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videojuego',
            name='consolaCompatible',
        ),
        migrations.AddField(
            model_name='videojuego',
            name='nombreConsola',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='consolaApp.consola'),
        ),
    ]
